### ISSUE TITLE
Run DLC file in an app using Docker

### ISSUE THREAD

**Issue by ayushmankumar7** [jackkosaian/snpe-docker#1]
Firstly, I would like to thank you for this helpful repo. I am successfully able to convert my model to DLC. 
I wanted to run an Android App which runs my DLC file. 
My question is do I need to build my app within this docker container or is it possible to run it outside the container? 

I am currently using Windows 10. :)

**Comment by jackkosaian** [comment]
I'm glad you've found this repo useful!

I haven't used SNPE within an Android app, so my ability to help in this regard is pretty limited. That said, I believe you should be able to take the DLC file you obtained in the container and use it in an Android app external to the container.

**Comment by ayushmankumar7** [comment]
OKay. No Issues! ..... but yeah Thanks again :)
